TEX = pdflatex  -halt-on-error
BIB= bibtex
FIGURES = #if you have figure files you would like to rebuild on changes to, put them here
NAME = NAME #the prefix to your document files, e.g. to produce a document called thesis.pdf, use thesis

$(NAME).pdf:$(NAME).out.tex $(FIGURES) $(NAME).out.bbl
	@$(TEX) $< 
	@$(TEX) $<
	@$(BIB) $(NAME).out
	@$(TEX) $< 
	@$(TEX) $<

$(NAME).out.bbl: $(NAME).out.aux
	@$(TEX) $(NAME).out.tex
	@$(BIB) $(NAME).out

$(NAME).out.aux: $(NAME).out.tex
	@$(TEX) $<

$(NAME).out.tex: $(NAME).tex
	@$(TEX) $<
	./betterbib.py $(NAME).bib $< $(NAME).aux

clean:
	rm -rf *.out *.out.tex *.aux
