TEX = pdflatex  -halt-on-error #-interaction=batchmode
BIB= bibtex
FIGURES = 
NAME = NAME
.PHONY:all clean remote-start remote-stop mainbuild

all: remote-stop


remote-start:
	echo "Starting Build"
	#put any prebuild set-up here


remote-stop:mainbuild
	echo "Finished Build"
	#put any post-build tear down steps here


mainbuild:remote-start
	-$(MAKE) -k -s --no-print-directory $(NAME).pdf 


$(NAME).pdf:$(NAME).out.tex $(FIGURES) $(NAME).out.bbl
	@$(TEX) $< 
	@$(TEX) $<
	@$(BIB) $(NAME).out
	@$(TEX) $< 
	@$(TEX) $<

$(NAME).out.bbl: $(NAME).out.aux
	@$(TEX) $(NAME).out.tex
	@$(BIB) $(NAME).out

$(NAME).out.aux: $(NAME).out.tex
	@$(TEX) $<

$(NAME).out.tex: $(NAME).tex
	@$(TEX) $<
	./betterbib.py $(NAME).bib $< $(NAME).aux

    
